## SCANLINES
default:
  # shader affects retroarch shaders
  shader: crt/crt-pi
  # scanline affect fba2x
  scanline: true
snes:
  shader: crt/crt-pi
nes:
  shader: crt/crt-pi
n64:
<<<<<<< HEAD
  shader: interpolation/sharp-bilinear-scanlines
gba:
  shader: handheld/lcd-grid-v2
gb:
   shader: handheld/zfast-lcd
=======
  shader: retro/sharp-bilinear-scanlines
gba:
  shader: handheld/zfast-lcd
gb:
  shader: handheld/zfast-lcd
>>>>>>> ceb3ef73e8f02d43f361654d21cebd1b750fb079
  colorization: GB - DMG
gb2players:
  shader: handheld/zfast-lcd
  colorization: GB - DMG
gbc:
<<<<<<< HEAD
  shader: handheld/lcd-grid-v2
fds:
  shader: interpolation/sharp-bilinear-scanlines
virtualboy:
  shader: interpolation/sharp-bilinear-scanlines
# Sega
sg1000:
  shader: interpolation/sharp-bilinear-scanlines
=======
  shader: handheld/zfast-lcd
fds:
  shader: retro/sharp-bilinear-scanlines
virtualboy:
  shader: retro/sharp-bilinear-scanlines
# Sega
sg1000:
  shader: retro/sharp-bilinear-scanlines
>>>>>>> ceb3ef73e8f02d43f361654d21cebd1b750fb079
mastersystem:
  shader: crt/crt-pi
megadrive:
  shader: crt/crt-pi
gamegear:
<<<<<<< HEAD
  shader: handheld/lcd-grid-v2
sega32x:
  shader: crt/crt-pi
segacd:
  shader: interpolation/sharp-bilinear-scanlines
# Arcade
neogeo:
  shader: interpolation/sharp-bilinear-scanlines
neogeocd:
  shader: interpolation/sharp-bilinear-scanlines
mame:
  shader: interpolation/sharp-bilinear-scanlines
fba:
  shader: interpolation/sharp-bilinear-scanlines
naomi:
  shader: interpolation/sharp-bilinear-scanlines
atomiswave:
  shader: interpolation/sharp-bilinear-scanlines
#
ngp:
  shader: handheld/lcd-grid-v2
ngpc:
  shader: handheld/lcd-grid-v2
=======
  shader: handheld/zfast-lcd
sega32x:
  shader: crt/crt-pi
segacd:
  shader: retro/sharp-bilinear-scanlines
# Arcade
neogeo:
  shader: retro/sharp-bilinear-scanlines
neogeocd:
  shader: retro/sharp-bilinear-scanlines
mame:
  shader: retro/sharp-bilinear-scanlines
fba:
  shader: retro/sharp-bilinear-scanlines
naomi:
  shader: retro/sharp-bilinear-scanlines
atomiswave:
  shader: retro/sharp-bilinear-scanlines
#
ngp:
  shader: handheld/zfast-lcd
ngpc:
  shader: handheld/zfast-lcd
>>>>>>> ceb3ef73e8f02d43f361654d21cebd1b750fb079
gw:
  shader: crt/crt-pi
vectrex:
  shader: crt/crt-pi
lynx:
<<<<<<< HEAD
  shader: handheld/lcd-grid-v2
lutro:
  shader: interpolation/sharp-bilinear-scanlines
wswan:
  shader: handheld/lcd-grid-v2
wswanc:
  shader: handheld/lcd-grid-v2
=======
  shader: handheld/zfast-lcd
lutro:
  shader: retro/sharp-bilinear-scanlines
wswan:
  shader: handheld/zfast-lcd
wswanc:
  shader: handheld/zfast-lcd
>>>>>>> ceb3ef73e8f02d43f361654d21cebd1b750fb079
pcengine:
  shader: crt/crt-pi
pcenginecd:
  shader: crt/crt-pi
supergrafx:
  shader: crt/crt-pi
atari800:
<<<<<<< HEAD
  shader: interpolation/sharp-bilinear-scanlines
atari2600:
  shader: interpolation/sharp-bilinear-scanlines
atari5200:
  shader: interpolation/sharp-bilinear-scanlines
atari7800:
  shader: interpolation/sharp-bilinear-scanlines
=======
  shader: retro/sharp-bilinear-scanlines
atari2600:
  shader: retro/sharp-bilinear-scanlines
atari5200:
  shader: retro/sharp-bilinear-scanlines
atari7800:
  shader: retro/sharp-bilinear-scanlines
>>>>>>> ceb3ef73e8f02d43f361654d21cebd1b750fb079
prboom:
  shader: crt/crt-pi
psx:
  shader: crt/crt-pi
colecovision:
  shader: crt/crt-pi
# Computers
msx:
<<<<<<< HEAD
  shader: interpolation/sharp-bilinear-scanlines
msx1:
  shader: interpolation/sharp-bilinear-scanlines
msx2:
  shader: interpolation/sharp-bilinear-scanlines
=======
  shader: retro/sharp-bilinear-scanlines
msx1:
  shader: retro/sharp-bilinear-scanlines
msx2:
  shader: retro/sharp-bilinear-scanlines
>>>>>>> ceb3ef73e8f02d43f361654d21cebd1b750fb079
amiga:
  shader: crt/crt-pi
amstradcpc:
  shader: crt/crt-pi
atarist:
  shader: crt/crt-pi
zxspectrum:
<<<<<<< HEAD
  shader: interpolation/sharp-bilinear-scanlines
odyssey2:
  shader: interpolation/sharp-bilinear-scanlines
zx81:
  shader: interpolation/sharp-bilinear-scanlines
pcfx:
  shader: interpolation/sharp-bilinear-scanlines
x68000:
  shader: interpolation/sharp-bilinear-scanlines
=======
  shader: retro/sharp-bilinear-scanlines
odyssey2:
  shader: retro/sharp-bilinear-scanlines
zx81:
  shader: retro/sharp-bilinear-scanlines
pcfx:
  shader: retro/sharp-bilinear-scanlines
x68000:
  shader: retro/sharp-bilinear-scanlines
>>>>>>> ceb3ef73e8f02d43f361654d21cebd1b750fb079
pc98:
  shader: crt/crt-pi
channelf:
  shader: crt/crt-pi
thomson:
<<<<<<< HEAD
  shader: crt/crt-pi
=======
  shader: crt/crt-pi
>>>>>>> ceb3ef73e8f02d43f361654d21cebd1b750fb079
